name: Build and upload Python Package to pypi.org

on:
  release:
    types: [created]

jobs:
  pypi-publish:
    timeout-minutes: 20

    runs-on: ubuntu-latest
    
    permissions:
      # See https://docs.pypi.org/trusted-publishers/using-a-publisher/
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine build

      - name: Build
        env:
          TWINE_PASSWORD: ${{ secrets.PUBLIC_PYPI_PASSWORD }}
        run: |
          pip install build
          python -m build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
