name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    timeout-minutes: 120

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.11']

    steps:
      - uses: actions/checkout@v4
        timeout-minutes: 10

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install -c ci-constraints.txt -r test-requirements.txt .
        timeout-minutes: 10

      - name: Test
        run: |
          python -m unittest
        timeout-minutes: 60
